### ISSUE TITLE
how to add external jquery/js files ?

### ISSUE THREAD

**Issue by ShahabHomayouni** [laracasts/Vue-SPA-Essentials-Routing#2]
Hi, thanks for your tutorial but have a big problem, your project only have external css, how can add external js files, nowadays laracasts, use vue and Vue-router 
with load many external js files !!! can you help?

i have a spa project and I add external js files in main.html, but not really work correctly and what is the best way to add external js, bootstrap.js(how? I only can use my js, and I cannot install by npm) or the way I add mine?

can you make a brief tutorial to explain how laracasts or real project can use laravel/vue with spa pages? plz

**Comment by CaddyDz** [comment]
You can reference the JS external libraries via a CDN in your master layout blade template
This tutorial however is importing modules from node_modules directory so it requires NPM installation

**Comment by ShahabHomayouni** [comment]
@CaddyDz I have a custom.js file which cannot use CDN or npm!
how can I use them?
I imported from the public folder, but not work correctly !!!

**Comment by CaddyDz** [comment]
You need NPM to resolve the dependencies  
It's too much work to resolve them by yourself and it may take forever

**Comment by ShahabHomayouni** [comment]
@CaddyDz thanks
